remote_theme: https://github.com/just-the-docs/just-the-docs
title: Grambulate.js Docs
color_scheme: dark
logo: "/assets/images/grambulatejsdocs.png"
aux_links:
  "grambulate.js on npm":
    - "https://www.npmjs.com/package/grambulate.js"
  "kapios.dev":
    - "https://kapios.dev"
gh_edit_link: false
plugins:
  - jekyll-default-layout
  - jekyll-remote-theme
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red